# SELECT E3.ID
# FROM ECOLI_DATA E1
#     JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
#     JOIN ECOLI_DATA E3 ON E2.ID = E3.PARENT_ID
# WHERE E1.PARENT_ID IS NULL
WITH RECURSIVE GenerationCTE AS (
    SELECT ID, PARENT_ID, 1 AS generation
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, G.generation + 1
    FROM ECOLI_DATA E
    JOIN GenerationCTE G ON E.PARENT_ID = G.ID
    WHERE G.generation < 3
)
SELECT ID
FROM GenerationCTE
WHERE generation = 3
ORDER BY ID;