WITH TEMP AS (
    SELECT PARENT_ID, COUNT(*) CNT
    FROM ECOLI_DATA
    GROUP BY 1
)

SELECT ID,
    CASE WHEN ID IN (SELECT PARENT_ID FROM TEMP) THEN CNT
    ELSE 0 END CHILD_COUNT
FROM ECOLI_DATA E
    LEFT JOIN TEMP T ON E.ID = T.PARENT_ID
