# WITH DATE AS (
#     SELECT CAR_ID,
#         CASE WHEN START_DATE > '20221130' OR END_DATE < '20221101' THEN 1
#         ELSE 0 END KK
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# )
# SELECT *
# FROM DATE

SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, DAILY_FEE * 30 * (100 - REPLACE(DISCOUNT_RATE, '%','')) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                         WHERE (C.start_date <= '2022-11-30' AND C.end_date >= '2022-11-01') OR (C.start_date >= '2022-11-01' AND C.end_date <= '2022-11-30')
                        )
HAVING FEE < 2000000 AND FEE >= 500000
ORDER BY 3 DESC, 2, 1 DESC