WITH TEMP AS (
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TEMP
WHERE RN = 1
ORDER BY 1 DESC