WITH TEMP AS (
    SELECT ID, (PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC))*100 RN
    FROM ECOLI_DATA
)
SELECT ID,
    CASE WHEN RN <= 25 THEN 'CRITICAL'
    WHEN RN <= 50 THEN 'HIGH'
    WHEN RN <= 75 THEN 'MEDIUM'
    ELSE 'LOW' END COLONY_NAME
FROM TEMP
ORDER BY 1