WITH TEMP AS (
    SELECT WRITER_ID, COUNT(*) CNT
    FROM USED_GOODS_BOARD
    GROUP BY 1
    HAVING CNT >= 3
)

SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) '전체주소',
    CONCAT(SUBSTR(TLNO,1,3), '-', SUBSTR(TLNO,4,4), '-', SUBSTR(TLNO,8,4)) '전화번호'
FROM USED_GOODS_USER U
    JOIN TEMP T ON U.USER_ID = T.WRITER_ID
ORDER BY 1 DESC