# WITH TEMP AS (
#     SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, DISTINCT(U.USER_ID)
#     FROM USER_INFO U
#         JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
#     WHERE GENDER IS NOT NULL
# )
# SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT(USER_ID)) USERS
# FROM TEMP
# GROUP BY 1,2,3
# ORDER BY 1,2,3

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO U
    JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3