WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA E
        JOIN CTE C ON C.ID = E.PARENT_ID
)
SELECT COUNT(*) COUNT, GENERATION
FROM CTE C
    LEFT JOIN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA) T ON C.ID = T.PARENT_ID
WHERE T.PARENT_ID IS NULL
GROUP BY 2
ORDER BY 2