WITH RECURSIVE CTE AS (
    SELECT PARENT_ID, ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.PARENT_ID, E.ID, GENERATION + 1
    FROM CTE C
        JOIN ECOLI_DATA E ON C.ID = E.PARENT_ID
)
SELECT COUNT(*) COUNT, GENERATION
FROM CTE C
    LEFT JOIN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA) E 
    ON C.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NULL
GROUP BY 2
ORDER BY 2