WITH TEMP AS (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '20221016' BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT(C.CAR_ID),
    CASE WHEN CAR_ID IN (SELECT CAR_ID FROM TEMP) THEN '대여중'
    ELSE '대여 가능' END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
ORDER BY 1 DESC