# WITH TEMP AS (
#     SELECT PRODUCT_ID
#     FROM FOOD_ORDER
#     WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
# )

# SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE) TOTAL_SALES
# FROM FOOD_PRODUCT P
#     RIGHT JOIN TEMP T ON P.PRODUCT_ID = T.PRODUCT_ID
# GROUP BY 1

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY 1
ORDER BY 3 DESC, 1