WITH TEMP AS (
SELECT HISTORY_ID, CAR_ID,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE 0 END AS DIF
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT DISTINCT HISTORY_ID, 
    CASE WHEN DIF = 0 THEN FLOOR(DAILY_FEE * DATE_DIFF)
    ELSE FLOOR(DAILY_FEE * DATE_DIFF * (100 - DISCOUNT_RATE) / 100) END FEE
FROM TEMP T
    JOIN CAR_RENTAL_COMPANY_CAR C ON T.CAR_ID = C.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
    AND (DURATION_TYPE = DIF OR DIF = 0)
ORDER BY 2 DESC, 1 DESC