WITH TEMP AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY 1
)

SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN TEMP T ON F.FLAVOR = T.FLAVOR
GROUP BY 1
ORDER BY SUM(F.TOTAL_ORDER + T.TOTAL_ORDER) DESC
LIMIT 3