WITH RECURSIVE TEMP AS (
    SELECT 0 AS N
    UNION
    SELECT N + 1
    FROM TEMP
    WHERE N < 23
)
SELECT N AS HOUR, COUNT(O.DATETIME) COUNT
FROM TEMP T
    LEFT JOIN ANIMAL_OUTS O ON T.N = HOUR(O.DATETIME)
GROUP BY 1
ORDER BY 1