WITH TEMP AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '20220801' and '20221031'
    GROUP BY 1
    HAVING COUNT(*) >= 5
)
SELECT MONTH(START_DATE) MONTH, C.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    JOIN TEMP T ON C.CAR_ID = T.CAR_ID
WHERE START_DATE BETWEEN '20220801' and '20221031'
GROUP BY 1, 2
HAVING RECORDS != 0
ORDER BY 1, 2 DESC