WITH TEMP AS (
    SELECT FISH_TYPE, MAX(LENGTH) MAX
    FROM FISH_INFO
    GROUP BY 1
)

SELECT I.ID, FISH_NAME, LENGTH
FROM FISH_INFO I
    JOIN TEMP T ON I.FISH_TYPE = T.FISH_TYPE
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE LENGTH = T.MAX