WITH TEMP AS (
SELECT DEPT_ID, ROUND(AVG(SAL)) AVG_SAL
FROM HR_EMPLOYEES
GROUP BY 1
)
SELECT H.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT H
    JOIN TEMP T ON H.DEPT_ID = T.DEPT_ID
ORDER BY 3 DESC