# WITH TEMP AS (
#     SELECT CATEGORY, MAX(PRICE) MAX_PRICE
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자','국','김치','식용유')
#     GROUP BY 1
# )
# SELECT F.CATEGORY, PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT F
#     JOIN TEMP T ON F.CATEGORY = T.CATEGORY
# WHERE PRICE = MAX_PRICE
# ORDER BY 2 DESC

# ----------------------------------------

SELECT CATEGORY, PRICE  MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME,
    RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
) TEMP
WHERE RN = 1
ORDER BY 2 DESC