WITH A AS (
    SELECT CODE AS A_CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
B AS (
    SELECT CODE AS B_CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
C AS (
    SELECT SUM(CODE) AS C_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT
    CASE WHEN SKILL_CODE & (SELECT A_CODE FROM A) != 0 
        AND SKILL_CODE & (SELECT C_CODE FROM C) != 0 THEN 'A'
    WHEN SKILL_CODE & (SELECT B_CODE FROM B) != 0 THEN 'B'
    WHEN SKILL_CODE & (SELECT C_CODE FROM C) != 0 THEN 'C'
    ELSE NULL END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY 1, 2
